### ISSUE TITLE
RAML Extension Chain doesn't go far enough

### ISSUE THREAD

**Issue by Garethp** [mulesoft/oas-raml-converter#28]
So I have these files:

user_short.raml
```yaml
#% RAML 1.0 DataType

properties:
  user_id: string
```

user_standard.raml
```yaml
#% RAML 1.0 DataType

type: !include user_short.raml
properties:
  birthday: string
  gender:
    type: string
    enum: ['Male', 'Female', 'Non-Binary']
```

user_full.raml
```yaml
#% RAML 1.0 DataType

type: !include user_standard.raml
properties:
  country_code: string
```

When I convert to HTML with `raml2html`, it shows the `user_full` object as having the `user_id` property, but when I use this tool to convert to swagger, the definitions are:

```json
  "definitions": {
    "user_short": {
      "properties": {
        "user_id": {
          "type": "string"
        }
      },
      "required": [
        "user_id"
      ],
      "type": "object"
    },
    "user_standard": {
      "properties": {
        "birthday": {
          "type": "string"
        },
        "gender": {
          "enum": [
            "Male",
            "Female",
            "Non-Binary"
          ],
          "type": "string"
        },
        "user_id": {
          "type": "string"
        }
      },
      "required": [
        "birthday",
        "gender",
        "user_id"
      ],
      "type": "object"
    },
    "user_full": {
      "properties": {
        "country_code": {
          "type": "string"
        },
        "birthday": {
          "type": "string"
        },
        "gender": {
          "enum": [
            "Male",
            "Female",
            "Non-Binary"
          ],
          "type": "string"
        }
      },
      "required": [
        "country_code",
        "birthday",
        "gender"
      ],
      "type": "object"
    }
```

You can see that `user_standard` has `user_id`, and `user_full` has items from `user_standard`, but doesn't have `user_id` from `user_short`
