### ISSUE TITLE
Preserve !include, preserve "schemas"

### ISSUE THREAD

**Issue by sharkberto** [mulesoft/oas-raml-converter#29]
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#applying-security-schemes

`securitySchemes` should still have their schema locations preserved.

I think `schemas`, since deprecated in raml 1.0, can be replaced by `types`, followed by the `!include` statements, but without reference to a type, see below, looks like `string` is applied...

```
#%RAML 0.8
title: Flickr API
baseUri: https://api.flickr.com/services
version: test-version
securitySchemes:
  - oauth_2_0: !include securitySchemes/raml08_oauth_2_0.raml
  - tokenSchema: !include securitySchemes/tokenSchema.raml
schemas:
  - photoPost-xml: !include /schemas/photoPost-xml-schema.xsd
  - okResponse-xml: !include /schemas/okResponse-xml-schema.xsd
```

```
#%RAML 1.0
title: Flickr API
version: test-version
protocols:
  - HTTPS
baseUri: 'https://api.flickr.com/services'
securitySchemes:
  oauth_2_0: {}
  tokenSchema: {}
types:
  photoPost-xml:
    type: string
  okResponse-xml:
    type: string
```
