### ISSUE TITLE
In OAS30, inheriting schemas miss their required fields

### ISSUE THREAD

**Issue by jsamr** [mulesoft/oas-raml-converter#46]
`oas-raml-coverter version 1.1.35`

When inheriting from `Foo`, `FooFromBar` schema should have a `required` array with its field names in it.

I believe it is related to #43 since the schemas afflicted with the bug are also wrongly typed `string`.

[**Full reproduction**](https://github.com/jsamr/oas-raml-converter-missing-required)

### Raml definition

``` yaml
types:
  Foo:
    type: object
    properties:
      foo1:
        type: number
        required: true
  BarFromFoo:
    type: Foo
    properties:
      bar1:
        type: string
        required: true
```

### Expected output (oas3+json)

``` json
{
  "components": {
    "schemas": {
      "Foo": {
        "type": "object",
        "properties": {
          "foo1": {
            "type": "number"
          }
        },
        "required": [
          "foo1"
        ]
      },
      "BarFromFoo": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Foo"
          },
          {
            "properties": {
              "bar1": {
                "type": "string"
              },
              "bar2": {
                "type": "string"
              }
            },
            "type": "object"
          }
        ],
        "required": [
          "bar1",
          "bar2"
        ]
      }
    }
  }
}
```

### Observed output (oas3+json)

``` json
{
  "components": {
    "schemas": {
      "Foo": {
        "type": "object",
        "properties": {
          "foo1": {
            "type": "number"
          }
        },
        "required": [
          "foo1"
        ]
      },
      "BarFromFoo": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Foo"
          },
          {
            "properties": {
              "bar1": {
                "type": "string"
              },
              "bar2": {
                "type": "string"
              }
            },
            "type": "object"
          }
        ],
        "type": "string"
      }
    }
  }
}
```
