### ISSUE TITLE
In RAML 1 to OAS3 conversion, resource description should not be a lost semantic

### ISSUE THREAD

**Issue by jsamr** [mulesoft/oas-raml-converter#48]
From [OAS3 specifications](https://swagger.io/docs/specification/paths-and-operations/):

> Paths may have an optional short `summary` and a longer `description` for documentation purposes. This information is supposed to be relevant to all operations in this path. description can be multi-line and supports Markdown (CommonMark) for rich text representation.

**Example**

``` yaml
paths:
  /users/{id}:
    summary: Represents a user
    description: >
      This resource represents an individual user in the system.
      Each user is identified by a numeric `id`.
    get:
      ...
    patch:
      ...
    delete:
      ...
```
