### ISSUE TITLE
In OAS 20 to RAML 1 conversion, properties in RAML should be required: false when a required array is missing in OAS

### ISSUE THREAD

**Issue by arghasarkar** [mulesoft/oas-raml-converter#50]
When converting OAS 20 to RAML 1, the properties should be set ```required: false``` when no ```required``` array is present in the OAS as the default required value in OAS is **true** AND there are **more than one property** present.

If there is only one property, it's working fine. 

**OAS 20 (Source)**
``` 
 Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
```

**RAML 1 (Expected)**
```
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
        required: false
      name:
        type: string
        required: false
```
**RAML 1 (Observed)**
```
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
```
